### ISSUE TITLE
Mod fails to load correctly on a server

### ISSUE THREAD

**Issue by Boxbott** [Voliant/GlowingObsidian#1]
Hi! so I've never submitted a github report before so sorry if I've given you the wrong information, but here's what I think is needed to fix the issue.

 This is the message I received in my server logs right before the crash message:
 
 
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: main
Stacktrace:
        at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71) ~[forge-1.16.5-36.0.22.jar:36.0] {}
-- MOD modicum --
Details:
        Mod File: modicum-1.16.5-0.3.2 (2).jar
        Failure message: Modicum (modicum) has failed to load correctly
                java.lang.RuntimeException: Attempted to load class net/minecraftforge/client/event/GuiScreenEvent for invalid dist DEDICATED_SERVER
        Mod Version: 0.3.2
        Mod Issue URL: https://github.com/abigailfails/Modicum/issues
        Exception message: java.lang.RuntimeException: Attempted to load class net/minecraftforge/client/event/GuiScreenEvent for invalid dist DEDICATED_SERVER
Stacktrace:
        at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71) ~[forge-1.16.5-36.0.22.jar:36.0] {}
        at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~[modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.9.jar:?] {re:classloading}
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.9.jar:?] {re:classloading}
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_275] {}
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_275] {}
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756) ~[?:1.8.0_275] {}
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:138) ~[modlauncher-8.0.9.jar:?] {re:classloading}
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.9.jar:?] {re:classloading}
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_275] {}
        at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_275] {}
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[?:1.8.0_275] {}
        at java.lang.Class.privateGetPublicMethods(Class.java:2902) ~[?:1.8.0_275] {}
        at java.lang.Class.getMethods(Class.java:1615) ~[?:1.8.0_275] {}
        at net.minecraftforge.eventbus.EventBus.registerClass(EventBus.java:75) ~[eventbus-4.0.0.jar:?] {}
        at net.minecraftforge.eventbus.EventBus.register(EventBus.java:118) ~[eventbus-4.0.0.jar:?] {}
        at net.minecraftforge.fml.AutomaticEventSubscriber.lambda$inject$6(AutomaticEventSubscriber.java:75) ~[forge:?] {re:classloading}
        at java.util.ArrayList.forEach(ArrayList.java:1259) ~[?:1.8.0_275] {}
        at net.minecraftforge.fml.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:62) ~[forge:?] {re:classloading}
        at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:91) ~[forge:36.0] {re:classloading}
        at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?] {re:classloading}
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640) ~[?:1.8.0_275] {}
        at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1632) ~[?:1.8.0_275] {}
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_275] {}
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_275] {}
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_275] {re:computing_frames}
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175) ~[?:1.8.0_275] {}

**Comment by solarsonata** [comment]
Fixed in 8b2854a, curse release coming soon.
